world_origin:

  units: "LATLON" # {"UTM, "LATLON"}

  origin_x: 50.111875
  origin_y: 14.418418

safety_area:

  enabled: true

  horizontal:

    # the frame of reference in which the points are expressed
    frame_name: "latlon_origin"

    # polygon
    #
    # x, y [m] for any frame_name except latlon_origin
    # x = latitude, y = longitude [deg]  for frame_name=="latlon_origin"
    points: [
      50.111616, 14.418113,
      50.112125, 14.417883,
      50.112271, 14.418946,
      50.111756, 14.419021,
    ]

  vertical:

    # the frame of reference in which the max&min z is expressed
    frame_name: "world_origin"

    max_z: 15.0
    min_z: 1.0