location: .gitman
sources:
- name: gazebo_plugins
  type: git
  repo: git@mrs.felk.cvut.cz:uvdd/gazebo-plugins.git
  sparse_paths:
  -
  rev: master
  link: gazebo_plugins
  scripts:
  - git submodule update --init --recursive
sources_locked:
- name: gazebo_plugins
  type: git
  repo: git@mrs.felk.cvut.cz:uvdd/gazebo-plugins.git
  sparse_paths:
  -
  rev: 5cddf4aba420d78a64b4e2c80eb04d107a69e704
  link: gazebo_plugins
  scripts:
  - git submodule update --init --recursive
