targets:
  - uvdar_ids: [12,13,14,15]
    uwb_id: 0
  - uvdar_ids: [66]
    uwb_id: 1
  - uvdar_ids: [66]
    uwb_id: 2
  - uvdar_ids: [66]
    uwb_id: 3
  - uvdar_ids: [66]
    uwb_id: 4
  - uvdar_ids: [66]
    uwb_id: 5
  - uvdar_ids: [66]
    uwb_id: 6
  - uvdar_ids: [66]
    uwb_id: 7
  - uvdar_ids: [66]
    uwb_id: 8
  - uvdar_ids: [66]
    uwb_id: 9
  - uvdar_ids: [66]
    uwb_id: 10
  - uvdar_ids: [66]
    uwb_id: 11
  - uvdar_ids: [66]
    uwb_id: 12
  - uvdar_ids: [66]
    uwb_id: 13
  - uvdar_ids: [66]
    uwb_id: 14
  - uvdar_ids: [66]
    uwb_id: 15
  - uvdar_ids: [66]
    uwb_id: 16
  - uvdar_ids: [66]
    uwb_id: 17
  - uvdar_ids: [66]
    uwb_id: 18
  - uvdar_ids: [66]
    uwb_id: 19
  - uvdar_ids: [66]
    uwb_id: 20

